name: Release and Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  cargo-publish:
    name: Cargo publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Publish or validate
        uses: ./.github/actions/publish-crate
        with:
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: false
          fail-if-version-published: false
